autolabeler:
  - label: 'chore'
    files:
      - '*.md'
      - '*.MD'
    branch:
      - '/docs{0,1}\/.+/'
  - label: 'bug'
    branch:
      - 'fix*'
    title:
      - '/fix/i'
  - label: 'enhancement'
    branch:
      - '/feature\/.+/'
categories:
  - title: 'Features'
    labels:
      - 'feature'
      - 'enhancement'
  - title: 'Bug Fixes'
    labels:
      - 'fix'
      - 'bugfix'
      - 'bug'
  - title: 'Maintenance'
    label: 'chore'
name-template: 'vNext'
tag-template: 'vNext'
change-template: '- $TITLE (#$NUMBER by @$AUTHOR)'
change-title-escapes: '\<*_&' # You can add # and @ to disable mentions, and add ` to disable code blocks.
template: |
  ## Contributors
  $CONTRIBUTORS
  ## Changes
  $CHANGES
