autolabeler:
  - label: 'chore'
    files:
      - '*.md'
      - '*.MD'
  - label: 'docs'
    files:
      - '/docs/*'
    branch:
      - '/docs/i'
  - label: 'bug'
    branch:
      - '/fix/i'
      - '/bug/i'
    title:
      - '/fix/i'
      - '/bug/i'
  - label: 'enhancement'
    branch:
      - '/feature/i'
categories:
  - title: 'Features'
    labels:
      - 'feature'
      - 'enhancement'
  - title: 'Bug Fixes'
    labels:
      - 'fix'
      - 'bugfix'
      - 'bug'
  - title: 'Maintenance'
    labels: 
      - 'chore'
      - 'docs'
name-template: 'vNext'
tag-template: 'vNext'
change-template: '- $TITLE (#$NUMBER by @$AUTHOR)'
change-title-escapes: '\<*_&' # You can add # and @ to disable mentions, and add ` to disable code blocks.
template: |
  ## Contributors
  $CONTRIBUTORS
  ## Changes
  $CHANGES
